let eGQ = [];
let eGA = [];
//Vi har lavet spørgsmål med forskellig sværhedsgrad, men kan ikke nå at implementere en mulighed for at vælge
//sværhedsgrad, så 
var eGeographyQ = ["What is the capital of Sweden?", "What is the capital of Norway?", "Which country is the biggest in the world?", "Copenhagen is the capital of…?", "What is the capital of Germany?", "Paris is the capital of…?", "Brussels is the capital of…?", "Athens is the capital of…?", "Which country is the best country?", "Which country is the most populated?", "Name a country starting with a V", "Which country has the longest coastline?", "What is the capital of Finland?", "Which country has the Kuala Lumpur as the capital?", "What is the capital of Spain?", "Name a country ending with the letter L", "Name the country with K as the last letter", "Name a country with the last letter M", "The capital of Canada is…?", "The Capital of Egypt is…?", "How many countries exist officially?", "Which country has the biggest number of neighbouring countries?", "Name the capital of Australia?", "Name a country with 8 neighbouring countries", "How many countries in the EU?", "What country is the smallest in the world?", "Country furthest from Denmark?", "Name the country with the longest coastline?", "What country is the least populated in the world?", "Lomé is the capital of…?"];
var eGeographyA = ["Stockholm", "Oslo", "Russia", "Denmark", "Berlin", "France", "Belgium", "Greece", "Denmark", "China", "Vanuatu, Venezuela or Vietnam", "Canada", "Helsinki", "Malaysia", "Madrid", "Nepal, Portugal, Senegal, Brazil or Israel", "Denmark", "Belgium, United Kingdom or Vietnam", "Ottawa", "Cairo", "195", "Russia (with 16)", "Canberra", "France, Austria, Turkey, Serbia, Tanzania or Zambia", "27", "Vatican City", "New Zealand", "Canada", "Vatican City (about 800 people)", "Togo"];

var mGeographyQ = ["Name a country starting with a V", "Which country has the longest coastline?", "What is the capital of Finland?", "Which country has the Kuala Lumpur as the capital?", "What is the capital of Spain?", "Name a country ending with the letter L", "Name the country with K as the last letter", "Name a country with the last letter M", "The capital of Canada is…?", "The Capital of Egypt is…?"];
var mGeographyA = ["Vanuatu, Venezuela or Vietnam", "Canada", "Helsinki", "Malaysia", "Madrid", "Nepal, Portugal, Senegal, Brazil or Israel", "Denmark", "Belgium, United Kingdom or Vietnam", "Ottawa", "Cairo"];

var hGeographyQ = ["How many countries exist officially?", "Which country has the biggest number of neighbouring countries?", "Name the capital of Australia?", "Name a country with exactly 8 neighbouring countries", "How many countries in the EU?", "What country is the smallest in the world?", "Country furthest from Denmark?", "Name the country with the longest coastline?", "What country is the least populated in the world?", "Lomé is the capital of…?"];
var hGeographyA = ["195", "Russia (with 16)", "Canberra", "France, Austria, Turkey, Serbia, Tanzania or Zambia", "27", "Vatican City", "New Zealand", "Canada", "Vatican City (about 800 people)", "Togo"];

var eMathsQ = ["2+5", "9-4", "2∙3", "4/2", "10∙2", "3∙4", "17+5", "23+8", "41-17", "32-9"];
var eMathsA = ["7", "5", "6", "2", "20", "12", "22", "31", "24", "23"];

var mMathsQ = ["9∙19", "", "", "", "", "", "", "", "", ""];
var mMathsA = ["117", "", "", "", "", "", "", "", "", ""];

var hMathsQ = ["144/32", "", "", "", "", "", "", "", "", ""];
var hMathsA = ["4.5", "", "", "", "", "", "", "", "", ""];

var ePopcultureQ = ["What does Hakuna Matata mean?", "What movie in 2019 topped Avatar as the highest-grossing film of all time?", "Which tech entrepreneur wanted to name his son X Æ A-12?", "Which country is ABBA from?", "Who has the hit singles “Perfect” and “Shape of You”?", "Who were the lead actors in the movie Twilight?", "Which movies is the line “Life is like a box of chocolate” from?", "What famous Christmas song is Mariah Carey known for?", "Name Donald Duck's three nephews", "When will Queen Elizabeth II die?", "What is the name of Ariel and Prince Eric’s daughter?", "Which Disney Princess sings “Once Upon a Dream”?", "How many Star Wars movies are there (not including spin-offs like Rogue One: A Star Wars Story and Solo)?", "Who was the drummer for The Beatles?", "How many movies are there in the film series The Godfather?", "How many movies has Tom Hanks been in?", "How many ghosts are there in A Christmas Carol?", "What is Tim Burton’s 1993 famous Christmas movie?", "What company has used Santa Claus in its advertisements every year since 1931?", "Black Panther starred which famous actor?", "What is the real name of Joe Exotic (Tiger King)?", "How many kids does Angelina Jolie have?", "What year did Disneyland open?", "What is the name of Wendy’s dog in Peter Pan?", "How many brothers does Prince Hans of the Southern Isles have in Frozen?", "What was the first music video played on MTV?", "What was Freddie Mercury’s real name?", "Which movie (adjusted for inflation) is the highest-grossing movie to date?", "What was the first Pixar movie", "What year was Britney Spears’ album Oops!… I Did It Again released?"];
var ePopcultureA = ["No worries", "Avengers: Endgame", "Elon Musk", "Sweden", "Ed Sheeran", "Robert Pattinson and Kristen Stewart", "Forrest Gump", "All I Want for Christmas Is You", "Louie, Dewey, and Huey", "Never (she's obviously immortal)", "Princess Melody", "Aurora (Sleeping Beauty)", "9", "Ringo Starr", "3", "More than 72", "Four (Christmas Past, Christmas Present, Christmas Future & Jacob Marley)", "The Nightmare Before Christmas", "Coca-Cola", "Chadwick Boseman", "Joseph Allen Maldonado-Passage", "6", "1955", "Nana", "12", "Video Killed the Radio Star", "Frederick Bulsara", "Gone with the Wind", "Toy Story", "2000"];

var mPopcultureQ = ["What is the name of Ariel and Prince Eric’s daughter?", "Which Disney Princess sings “Once Upon a Dream”?", "How many Star Wars movies are there (not including spin-offs like Rogue One: A Star Wars Story and Solo)?", "Who was the drummer for The Beatles?", "How many movies are there in the film series The Godfather?", "How many movies has Tom Hanks been in?", "How many ghosts are there in A Christmas Carol?", "What is Tim Burton’s 1993 famous Christmas movie?", "What company has used Santa Claus in its advertisements every year since 1931?", "Black Panther starred which famous actor?"];
var mPopcultureA = ["Princess Melody", "Aurora (Sleeping Beauty)", "9", "Ringo Starr", "3", "More than 72", "Four (Christmas Past, Christmas Present, Christmas Future & Jacob Marley)", "The Nightmare Before Christmas", "Coca-Cola", "Chadwick Boseman"];

var hPopcultureQ = ["What is the real name of Joe Exotic (Tiger King)?", "How many kids does Angelina Jolie have?", "What year did Disneyland open?", "What is the name of Wendy’s dog in Peter Pan?", "How many brothers does Prince Hans of the Southern Isles have in Frozen?", "What was the first music video played on MTV?", "What was Freddie Mercury’s original name?", "Which movie (adjusted for inflation) is the highest-grossing movie to date?", "What was the first Pixar movie", "What year was Britney Spears’ album Oops!… I Did It Again released?"];
var hPopcultureA = ["Joseph Allen Maldonado-Passage", "6", "1955", "Nana", "12", "Video Killed the Radio Star", "Frederick Bulsara", "Gone with the Wind", "Toy Story", "2000"];

var eRandomQ = ["How many hours in a day?", "", "", "", "", "", "", "", "", ""];
var eRandomA = ["24", "", "", "", "", "", "", "", "", ""];

var mRandomQ = ["How old is Mette Frederiksen?", "", "", "", "", "", "", "", "", ""];
var mRandomA = ["44 years old", "", "", "", "", "", "", "", "", ""];

var hRandomQ = ["How many hours in year?", "", "", "", "", "", "", "", "", ""];
var hRandomA = ["About 8765.81277 hours", "", "", "", "", "", "", "", "", ""];
